"""
REEL GOD — Memory System
==========================
SQLite-backed persistent memory. The agent remembers everything:
posts, performance, decisions, trends, and what the commander likes.
"""

import sqlite3
import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional


class AgentMemory:
    """
    Persistent memory for REEL GOD.
    Stores and retrieves all knowledge the agent accumulates over time.
    """

    def __init__(self, db_path: Path):
        self.db_path = str(db_path)
        self._init_db()

    # ──────────────────────────────────────────────────────────────────────
    #  DATABASE SETUP
    # ──────────────────────────────────────────────────────────────────────

    def _connect(self):
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row  # Return dict-like rows
        conn.execute("PRAGMA journal_mode=WAL;")  # Better concurrency
        return conn

    def _init_db(self):
        """Create all database tables if they don't exist."""
        with self._connect() as conn:
            conn.executescript("""
                -- Learned rules and feedback from the commander
                CREATE TABLE IF NOT EXISTS commander_rules (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    rule        TEXT NOT NULL,
                    category    TEXT DEFAULT 'general',
                    created_at  TEXT DEFAULT (datetime('now')),
                    is_active   INTEGER DEFAULT 1
                );

                -- Content ideas generated by the agent
                CREATE TABLE IF NOT EXISTS content_ideas (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    title       TEXT NOT NULL,
                    style       TEXT NOT NULL,
                    story       TEXT NOT NULL,
                    script      TEXT,
                    mood        TEXT,
                    status      TEXT DEFAULT 'pending',
                    created_at  TEXT DEFAULT (datetime('now')),
                    approved_at TEXT,
                    rejected_at TEXT,
                    reject_reason TEXT
                );

                -- Published posts and their analytics
                CREATE TABLE IF NOT EXISTS posts (
                    id              INTEGER PRIMARY KEY AUTOINCREMENT,
                    idea_id         INTEGER REFERENCES content_ideas(id),
                    instagram_id    TEXT,
                    title           TEXT,
                    style           TEXT,
                    video_path      TEXT,
                    thumbnail_path  TEXT,
                    caption         TEXT,
                    hashtags        TEXT,
                    music_track     TEXT,
                    posted_at       TEXT,
                    views           INTEGER DEFAULT 0,
                    likes           INTEGER DEFAULT 0,
                    comments        INTEGER DEFAULT 0,
                    saves           INTEGER DEFAULT 0,
                    shares          INTEGER DEFAULT 0,
                    reach           INTEGER DEFAULT 0,
                    engagement_rate REAL DEFAULT 0.0,
                    last_updated    TEXT DEFAULT (datetime('now'))
                );

                -- Agent thoughts and decisions (its reasoning log)
                CREATE TABLE IF NOT EXISTS thoughts (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    category    TEXT NOT NULL,
                    content     TEXT NOT NULL,
                    created_at  TEXT DEFAULT (datetime('now'))
                );

                -- Trends the agent has observed
                CREATE TABLE IF NOT EXISTS trends (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    platform    TEXT DEFAULT 'instagram',
                    topic       TEXT NOT NULL,
                    hashtag     TEXT,
                    score       REAL DEFAULT 0.0,
                    observed_at TEXT DEFAULT (datetime('now')),
                    expires_at  TEXT
                );

                -- Performance analytics by style
                CREATE TABLE IF NOT EXISTS style_performance (
                    id              INTEGER PRIMARY KEY AUTOINCREMENT,
                    style           TEXT NOT NULL,
                    avg_views       REAL DEFAULT 0.0,
                    avg_likes       REAL DEFAULT 0.0,
                    avg_saves       REAL DEFAULT 0.0,
                    avg_engagement  REAL DEFAULT 0.0,
                    post_count      INTEGER DEFAULT 0,
                    last_updated    TEXT DEFAULT (datetime('now'))
                );

                -- Commander feedback and preferences
                CREATE TABLE IF NOT EXISTS commander_feedback (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    idea_id     INTEGER REFERENCES content_ideas(id),
                    feedback    TEXT NOT NULL,
                    sentiment   TEXT,
                    learned     TEXT,
                    created_at  TEXT DEFAULT (datetime('now'))
                );

                -- Music library cache
                CREATE TABLE IF NOT EXISTS music_library (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    title       TEXT NOT NULL,
                    artist      TEXT,
                    mood        TEXT,
                    genre       TEXT,
                    duration    REAL,
                    file_path   TEXT,
                    jamendo_id  TEXT,
                    source_url  TEXT,
                    used_count  INTEGER DEFAULT 0,
                    last_used   TEXT,
                    added_at    TEXT DEFAULT (datetime('now'))
                );

                -- Content Schedule table
                CREATE TABLE IF NOT EXISTS content_schedule (
                    id              INTEGER PRIMARY KEY AUTOINCREMENT,
                    day_name        TEXT NOT NULL,
                    date_str        TEXT NOT NULL,
                    style           TEXT NOT NULL,
                    theme           TEXT NOT NULL,
                    post_time       TEXT NOT NULL,
                    status          TEXT DEFAULT 'pending',
                    created_at      TEXT DEFAULT (datetime('now')),
                    published_at    TEXT,
                    post_id         INTEGER REFERENCES posts(id)
                );
            """)

    # ──────────────────────────────────────────────────────────────────────
    #  CONTENT IDEAS
    # ──────────────────────────────────────────────────────────────────────

    def save_idea(self, title: str, style: str, story: str,
                  script: str = None, mood: str = None) -> int:
        """Save a new content idea. Returns the idea ID."""
        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT INTO content_ideas (title, style, story, script, mood)
                   VALUES (?, ?, ?, ?, ?)""",
                (title, style, story, script, mood)
            )
            return cursor.lastrowid

    def get_pending_ideas(self) -> list:
        """Get all ideas waiting for commander approval."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM content_ideas WHERE status = 'pending' ORDER BY created_at DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    def approve_idea(self, idea_id: int):
        """Mark an idea as approved by commander."""
        with self._connect() as conn:
            conn.execute(
                "UPDATE content_ideas SET status='approved', approved_at=datetime('now') WHERE id=?",
                (idea_id,)
            )

    def reject_idea(self, idea_id: int, reason: str = ""):
        """Mark an idea as rejected by commander."""
        with self._connect() as conn:
            conn.execute(
                """UPDATE content_ideas
                   SET status='rejected', rejected_at=datetime('now'), reject_reason=?
                   WHERE id=?""",
                (reason, idea_id)
            )

    def get_idea(self, idea_id: int) -> Optional[dict]:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM content_ideas WHERE id=?", (idea_id,)
            ).fetchone()
            return dict(row) if row else None

    # ──────────────────────────────────────────────────────────────────────
    #  POSTS & ANALYTICS
    # ──────────────────────────────────────────────────────────────────────

    def save_post(self, idea_id: int, video_path: str, caption: str,
                  hashtags: str, music_track: str, title: str, style: str) -> int:
        """Record a post that has been published."""
        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT INTO posts
                   (idea_id, title, style, video_path, caption, hashtags, music_track, posted_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))""",
                (idea_id, title, style, video_path, caption, hashtags, music_track)
            )
            return cursor.lastrowid

    def update_post_analytics(self, post_id: int, views: int, likes: int,
                               comments: int, saves: int, shares: int, reach: int):
        """Update analytics for a published post."""
        engagement = (likes + comments + saves + shares) / max(reach, 1) * 100
        with self._connect() as conn:
            conn.execute(
                """UPDATE posts
                   SET views=?, likes=?, comments=?, saves=?, shares=?,
                       reach=?, engagement_rate=?, last_updated=datetime('now')
                   WHERE id=?""",
                (views, likes, comments, saves, shares, reach, engagement, post_id)
            )

    def get_recent_posts(self, limit: int = 10) -> list:
        """Get the most recent posts with analytics."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM posts ORDER BY posted_at DESC LIMIT ?", (limit,)
            ).fetchall()
            return [dict(r) for r in rows]

    def get_performance_summary(self) -> dict:
        """Get overall performance statistics across all posts."""
        with self._connect() as conn:
            row = conn.execute("""
                SELECT
                    COUNT(*) as total_posts,
                    AVG(views) as avg_views,
                    AVG(likes) as avg_likes,
                    AVG(saves) as avg_saves,
                    AVG(engagement_rate) as avg_engagement,
                    MAX(views) as max_views,
                    MAX(engagement_rate) as best_engagement
                FROM posts
            """).fetchone()
            
            # Best performing style
            best_style_row = conn.execute("""
                SELECT style, AVG(engagement_rate) as avg_eng
                FROM posts
                GROUP BY style
                ORDER BY avg_eng DESC
                LIMIT 1
            """).fetchone()

            result = dict(row) if row else {}
            if best_style_row:
                result["best_style"] = dict(best_style_row)
            return result

    def get_style_stats(self) -> list:
        """Get performance breakdown by content style."""
        with self._connect() as conn:
            rows = conn.execute("""
                SELECT
                    style,
                    COUNT(*) as post_count,
                    AVG(views) as avg_views,
                    AVG(likes) as avg_likes,
                    AVG(saves) as avg_saves,
                    AVG(engagement_rate) as avg_engagement
                FROM posts
                GROUP BY style
                ORDER BY avg_engagement DESC
            """).fetchall()
            return [dict(r) for r in rows]

    # ──────────────────────────────────────────────────────────────────────
    #  THOUGHTS & REASONING LOG
    # ──────────────────────────────────────────────────────────────────────

    def save_thought(self, content: str, category: str = "general"):
        """Log an agent thought or decision."""
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO thoughts (category, content) VALUES (?, ?)",
                (category, content)
            )

    def get_recent_thoughts(self, limit: int = 5, category: str = None) -> list:
        """Retrieve recent agent thoughts."""
        with self._connect() as conn:
            if category:
                rows = conn.execute(
                    "SELECT * FROM thoughts WHERE category=? ORDER BY created_at DESC LIMIT ?",
                    (category, limit)
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM thoughts ORDER BY created_at DESC LIMIT ?",
                    (limit,)
                ).fetchall()
            return [dict(r) for r in rows]

    # ──────────────────────────────────────────────────────────────────────
    #  TRENDS
    # ──────────────────────────────────────────────────────────────────────

    def save_trend(self, topic: str, hashtag: str = None,
                   score: float = 0.0, platform: str = "instagram",
                   expires_hours: int = 48):
        """Store an observed trend."""
        expires_at = (datetime.now() + timedelta(hours=expires_hours)).isoformat()
        with self._connect() as conn:
            conn.execute(
                """INSERT INTO trends (platform, topic, hashtag, score, expires_at)
                   VALUES (?, ?, ?, ?, ?)""",
                (platform, topic, hashtag, score, expires_at)
            )

    def get_active_trends(self, limit: int = 20) -> list:
        """Get currently active (non-expired) trends."""
        with self._connect() as conn:
            rows = conn.execute(
                """SELECT * FROM trends
                   WHERE expires_at > datetime('now') OR expires_at IS NULL
                   ORDER BY score DESC, observed_at DESC
                   LIMIT ?""",
                (limit,)
            ).fetchall()
            return [dict(r) for r in rows]

    # ──────────────────────────────────────────────────────────────────────
    #  COMMANDER FEEDBACK
    # ──────────────────────────────────────────────────────────────────────

    def save_feedback(self, feedback: str, idea_id: int = None,
                      sentiment: str = None, learned: str = None):
        """Store commander feedback so the agent can learn from it."""
        with self._connect() as conn:
            conn.execute(
                """INSERT INTO commander_feedback (idea_id, feedback, sentiment, learned)
                   VALUES (?, ?, ?, ?)""",
                (idea_id, feedback, sentiment, learned)
            )

    def get_all_feedback(self) -> list:
        """Get all feedback the commander has given."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM commander_feedback ORDER BY created_at DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    # ──────────────────────────────────────────────────────────────────────
    #  MUSIC LIBRARY
    # ──────────────────────────────────────────────────────────────────────

    def save_music(self, title: str, artist: str, mood: str, genre: str,
                   file_path: str, jamendo_id: str = None,
                   source_url: str = None, duration: float = 0.0) -> int:
        """Add a track to the local music library."""
        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT INTO music_library
                   (title, artist, mood, genre, duration, file_path, jamendo_id, source_url)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (title, artist, mood, genre, duration, file_path, jamendo_id, source_url)
            )
            return cursor.lastrowid

    def get_music_by_mood(self, mood: str, limit: int = 10) -> list:
        """Find tracks matching a specific mood."""
        with self._connect() as conn:
            rows = conn.execute(
                """SELECT * FROM music_library
                   WHERE mood LIKE ? OR genre LIKE ?
                   ORDER BY used_count ASC, RANDOM()
                   LIMIT ?""",
                (f"%{mood}%", f"%{mood}%", limit)
            ).fetchall()
            return [dict(r) for r in rows]

    def mark_music_used(self, music_id: int):
        """Track how often a music track is used."""
        with self._connect() as conn:
            conn.execute(
                "UPDATE music_library SET used_count=used_count+1, last_used=datetime('now') WHERE id=?",
                (music_id,)
            )

    def save_rule(self, rule: str, category: str = 'general') -> int:
        """Save a learned rule or commander preference."""
        with self._connect() as conn:
            cursor = conn.execute(
                "INSERT INTO commander_rules (rule, category) VALUES (?, ?)",
                (rule, category)
            )
            return cursor.lastrowid

    def get_active_rules(self) -> list:
        """Retrieve all active commander rules."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM commander_rules WHERE is_active = 1 ORDER BY created_at DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    def delete_rule(self, rule_id: int):
        """Deactivate or remove a rule."""
        with self._connect() as conn:
            conn.execute("UPDATE commander_rules SET is_active = 0 WHERE id = ?", (rule_id,))

    # ──────────────────────────────────────────────────────────────────────
    #  STATS & REPORTING
    # ──────────────────────────────────────────────────────────────────────

    def get_full_memory_snapshot(self) -> dict:
        """Return a complete snapshot of the agent's memory for self-analysis."""
        return {
            "performance": self.get_performance_summary(),
            "style_stats": self.get_style_stats(),
            "active_trends": self.get_active_trends(10),
            "recent_posts": self.get_recent_posts(5),
            "commander_feedback": self.get_all_feedback(),
            "recent_thoughts": self.get_recent_thoughts(3),
        }

    # ──────────────────────────────────────────────────────────────────────
    #  CONTENT SCHEDULE & ANALYTICS LOOP HELPERS
    # ──────────────────────────────────────────────────────────────────────

    def save_schedule_day(self, day_name: str, date_str: str, style: str, theme: str, post_time: str) -> int:
        """Insert or replace a calendar schedule day."""
        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT OR REPLACE INTO content_schedule (day_name, date_str, style, theme, post_time, status)
                   VALUES (?, ?, ?, ?, ?, 'pending')""",
                (day_name, date_str, style, theme, post_time)
            )
            return cursor.lastrowid

    def get_active_schedule(self) -> list:
        """Retrieve all schedule entries ordered chronologically."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM content_schedule ORDER BY date_str ASC, post_time ASC"
            ).fetchall()
            return [dict(r) for r in rows]

    def get_pending_scheduled_slots(self, current_date_str: str, current_time_str: str) -> list:
        """Retrieve all pending schedule slots that are due for publishing."""
        with self._connect() as conn:
            rows = conn.execute(
                """SELECT * FROM content_schedule
                   WHERE status = 'pending' AND date_str <= ? AND post_time <= ?
                   ORDER BY date_str ASC, post_time ASC""",
                (current_date_str, current_time_str)
            ).fetchall()
            return [dict(r) for r in rows]

    def mark_slot_published(self, slot_id: int, post_id: int):
        """Mark a schedule slot as successfully published, linking it to the post ID."""
        with self._connect() as conn:
            conn.execute(
                """UPDATE content_schedule
                   SET status = 'published', published_at = datetime('now'), post_id = ?
                   WHERE id = ?""",
                (post_id, slot_id)
            )

    def get_all_published_posts_with_ig_ids(self) -> list:
        """Get all posts that have been deployed to Instagram for metric updates."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM posts WHERE instagram_id IS NOT NULL AND instagram_id != 'None'"
            ).fetchall()
            return [dict(r) for r in rows]

    def update_post_analytics(self, post_id: int, metrics: dict):
        """Update metrics and compute the resulting engagement rate."""
        views = metrics.get("views", 0)
        likes = metrics.get("likes", 0)
        comments = metrics.get("comments", 0)
        saves = metrics.get("saves", 0)
        shares = metrics.get("shares", 0)
        reach = metrics.get("reach", 0)

        # Engagement rate = (likes + comments) / views * 100
        engagement_rate = 0.0
        if views > 0:
            engagement_rate = round(((likes + comments) / views) * 100, 2)

        with self._connect() as conn:
            conn.execute(
                """UPDATE posts
                   SET views = ?, likes = ?, comments = ?, saves = ?, shares = ?, reach = ?, engagement_rate = ?, last_updated = datetime('now')
                   WHERE id = ?""",
                (views, likes, comments, saves, shares, reach, engagement_rate, post_id)
            )

            # Update style performance aggregator table
            row = conn.execute("SELECT style FROM posts WHERE id = ?", (post_id,)).fetchone()
            if row:
                style = row["style"]
                # Re-calculate averages for this style
                style_rows = conn.execute(
                    """SELECT AVG(views) as av, AVG(likes) as al, AVG(saves) as asv, AVG(engagement_rate) as ae, COUNT(id) as cnt
                       FROM posts WHERE style = ?""", (style,)
                ).fetchone()
                
                if style_rows and style_rows["cnt"] > 0:
                    conn.execute(
                        """INSERT OR REPLACE INTO style_performance (style, avg_views, avg_likes, avg_saves, avg_engagement, post_count, last_updated)
                           VALUES (?, ?, ?, ?, ?, ?, datetime('now'))""",
                        (style, style_rows["av"] or 0.0, style_rows["al"] or 0.0, style_rows["asv"] or 0.0, style_rows["ae"] or 0.0, style_rows["cnt"])
                    )

